#!/usr/bin/python

systems = {
        "Simple Pendulum": {
            "x": "y",
            "y": "sin(x)",
            "z": "0",
            "locations": [(0.5, 0.5)],
            "xlim": [-5, 5],
            "ylim": [-5, 5],
            "tmax": 25.0,
            "projection": "2D",
            },
        "Linear Oscillator":   {
            "x": "y",
            "y": "-omega * x - c * y",
            "z": "0",
            "params": {"c": 0.5, "omega": 1.0},
            "locations": [(0.5, 0.5)],
            "xlim": [-5, 5],
            "ylim": [-5, 5],
            "tmax": 25.0,
            "projection": "2D",
            },
        "Van Der Pol Oscillator":  {
            "x": "y",
            "y": "-x + mu * (1 - x*x)*y",
            "z": "0",
            "params": {"mu": 1.0},
            "locations": [(0.1, 0.1), (4.0, 4.0)],
            "xlim": [-5, 5],
            "ylim": [-5, 5],
            "tmax": 25.0,
            "projection": "2D",
            },
        "Lorentz attractor": {
            "x": "sigma * (y-x)",
            "y": "x * (rho - z) - y",
            "z": "x*y - beta * z",
            "params": {"sigma": 10.0, "beta": 8.0/3.0, "rho": 28.0},
            "xlim": [-20.0, 20.0],
            "ylim": [-30.0, 30.0],
            "zlim": [0.0, 50],
            "tmax": 100.0,
            "projection": "3D",
            "locations": [(0.5, 0.5)],
            },
        "Rossler attractor": {
            "x": "-y - z",
            "y": "x + a*y",
            "z": "b + z*(x - c)",
            "params": {"a": 0.1, "b": 0.1, "c": 14},
            "xlim": [-20.0, 20.0],
            "ylim": [-20.0, 20.0],
            "zlim": [-10.0, 30.0],
            "tmax": 100.0,
            "projection": "3D",
            "locations": [(-10.5, 10.5), (-10.5, 10.6)],
            },
        "Belousov-Zhabotinski": {
            "x": "a - x - 4*x*y/(1+x*x)",
            "y": "b*x *(1- y/(1+x*x))",
            "z": "0",
            "params": {"a": 10, "b": 1},
            "xlim": [0, 5],
            "ylim": [0, 10],
            "tmax": 50,
            "projection": "2D",
            "locations": [(4,4), (2,6)],
            }
#        "Duffing oscillator": {
#                "x": "y",
#                "y": "-d*y + x - x**3 + gamma*cos(w*z)",
#                "z": "1.0",
#                "xlim": [-10.0, 10.0],
#                "ylim": [-10.0, 10.0],
#                "zlim": [0, 50]
#                }
        }
